Repository ssafyhapy/freezetag-backend, pull requests merged in 2024-07, with the labels that each got.

#3 feat/#1/초기_엔티티_생성
  src/main/java/com/ssafy/freezetag/domain/common/BaseEntity.java
  src/main/java/com/ssafy/freezetag/domain/member/controller/.gitkeep
  src/main/java/com/ssafy/freezetag/domain/member/entity/Age.java
  src/main/java/com/ssafy/freezetag/domain/member/entity/Member.java
  src/main/java/com/ssafy/freezetag/domain/member/entity/MemberHistory.java
  src/main/java/com/ssafy/freezetag/domain/member/entity/MemberHobby.java
  src/main/java/com/ssafy/freezetag/domain/member/entity/MemberInterest.java
  src/main/java/com/ssafy/freezetag/domain/member/repository/.gitkeep
  src/main/java/com/ssafy/freezetag/domain/member/service/.gitkeep
  src/main/java/com/ssafy/freezetag/domain/recommend/controller/.gitkeep
  src/main/java/com/ssafy/freezetag/domain/recommend/entity/BalanceRecommend.java
  src/main/java/com/ssafy/freezetag/domain/recommend/repository/.gitkeep
  src/main/java/com/ssafy/freezetag/domain/recommend/service/.gitkeep
  src/main/java/com/ssafy/freezetag/domain/result/controller/.gitkeep
  src/main/java/com/ssafy/freezetag/domain/result/entity/BalanceResult.java
  src/main/java/com/ssafy/freezetag/domain/result/entity/IntroResult.java
  src/main/java/com/ssafy/freezetag/domain/result/entity/OXResult.java
  src/main/java/com/ssafy/freezetag/domain/result/entity/SelectedOption.java
  src/main/java/com/ssafy/freezetag/domain/result/repository/.gitkeep
  src/main/java/com/ssafy/freezetag/domain/result/service/.gitkeep
  src/main/java/com/ssafy/freezetag/domain/room/controller/.gitkeep
  src/main/java/com/ssafy/freezetag/domain/room/entity/MemberRoom.java
  src/main/java/com/ssafy/freezetag/domain/room/entity/Room.java
  src/main/java/com/ssafy/freezetag/domain/room/entity/RoomImage.java
  src/main/java/com/ssafy/freezetag/domain/room/repository/.gitkeep
  src/main/java/com/ssafy/freezetag/domain/room/service/.gitkeep
  src/main/java/com/ssafy/freezetag/global/.gitkeep
Labels: feature 🛠

#6 docs/#5/README_초기_파일_생성
  README.md
Labels: docs 📄

#8 test/#7/readme_수정_테스트
  README.md
Labels: test ✅

#10 refactor/#9/Member_엔티티_리팩토링
  src/main/java/com/ssafy/freezetag/domain/member/entity/Member.java
  src/main/java/com/ssafy/freezetag/domain/member/entity/MemberVisibility.java
Labels: refactoring ⚙️
